version: '3.8'
services:
  server:
    container_name: backend
    build: ./server/Business logic service/Auto.Ru/Auto.Ru.Web/
    restart: always
    ports:
      - '5000:3000'
    
  client:
    container_name: frontend
    build: ./client/
    restart: always
    ports:
      - '3000:3000'
    