version: '3.8'
services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_DATABASE: auto.ru
      MYSQL_ROOT_PASSWORD: "*K^rb%kVQH5$1I8WvL1CQerr"
    restart: unless-stopped
    networks:
      - backend
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql

  server:
    depends_on:
      - mysqldb
    container_name: backend
    build: ./server/Business logic service/Auto.Ru/Auto.Ru.Web/
    restart: always
    ports:
      - '5000:3000'
    
  client:
    depends_on:
      - server  
    container_name: frontend
    build: ./client/
    restart: always
    ports:
      - '3000:3000'

volumes: 
  db:

networks:
  backend:
  frontend:

    