version: "3"
services:
  server:
    build: ./server/Business logic service/Auto.Ru/Auto.Ru.Web/
    ports:
      - "8080:8080"
    container_name: backend
  client:
    build: ./client 
    ports:
      - "80:80"
    container_name: frontend